---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: neuvector-core
  namespace: fleet-default
spec:
  branch: testing
#  clientSecretName: <secretname>
  insecureSkipTLSVerify: false
  paths:
  - /apps/neuvector-core
  paused: false
  repo: https://github.com/spimmer/fleet-templates.git
#  targets:
#  - clusterName: <clustername>